server:
  port: 8080

spring:
  application:
    name: api-gateway
  kafka:
    bootstrap-servers:
      - 52.77.250.133:9092
    producer:
      acks: all
      compression-type: snappy
      properties:
        batch.size: 64000 # 64KB
        linger.ms: 1000   # 5s

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

security:
  facebook:
    clientId: 98123841002394711283
    clientSecret: 3DS9v9KWpt3TeCGWcISuOZOrMtunHn4c
  auth:
    login-url: /api/customers/login
    header-name: Authorization
    header-prefix: "Bearer "
    expiration-time: 864000000  # 10 days
    secret-key: 01Yd91OYRQGt4VbYHRxaMmnplggPjkZb