server:
  port: 8500

grpc:
  port: 8501

spring:
  application:
    name: product-auditing-service
  elasticsearch:
    rest:
      uris: localhost:9200

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
  instance:
    preferIpAddress: true