server:
  port: 8500

grpc:
  port: 8501

spring:
  application:
    name: product-auditing-service
  elasticsearch:
    rest:
      uris: 52.77.250.133:9200

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    non-secure-port: ${grpc.port}