server:
  port: 8000

grpc:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nab_customer
    username: root
    password: 123456789
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
