spring:
  application:
    name: product-auditing-worker
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: product-auditing-worker
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-offset-reset: latest

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

product-auditing-service:
  grpcserver:
    host: localhost
    port: 8501