version: '3.7'
services:
  zookeeper:
    image: debezium/zookeeper:1.4
    container_name: icommerce-zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - icommerce-network

  kafka:
    image: debezium/kafka:1.4
    container_name: icommerce-kafka
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_LISTENERS=INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
#      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:29092,OUTSIDE://localhost:9092
#      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    networks:
      - icommerce-network

  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: icommerce-kafka-manager
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=zookeeper:2181
      - APPLICATION_SECRET=letmein
    links:
      - kafka
      - zookeeper
    depends_on:
      - kafka
      - zookeeper
    networks:
      - icommerce-network

  mysql:
    image: mysql:8.0
    container_name: icommerce-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - icommerce-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: icommerce-elasticsearch
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - icommerce-network

  debezium:
    image: debezium/connect-jdbc-es:1.4
    container_name: icommerce-debezium
    build:
      context: debezium
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - mysql
      - elasticsearch
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium_connect_configs
      - OFFSET_STORAGE_TOPIC=debezium_connect_offsets
      - STATUS_STORAGE_TOPIC=debezium_source_connect_statuses
    networks:
      - icommerce-network

  redis:
    image: redis:6.2.1-alpine
    container_name: icommerce-redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - icommerce-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: icommerce-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    links:
      - redis
    depends_on:
      - redis
    networks:
      - icommerce-network

networks:
  icommerce-network:
    driver: bridge