version: '3.7'
services:
  kafka-manager:
    image: kafkamanager/kafka-manager:latest
    container_name: icommerce-kafka-manager
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=${PRIVATE_HOST_IP}:2181
      - APPLICATION_SECRET=icommerce
    networks:
      - icommerce-network

  mysql:
    image: mysql:8.0
    container_name: icommerce-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - icommerce-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: icommerce-elasticsearch
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=eEBrCXyeS6mmrZ7P
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - icommerce-network

  debezium:
    image: debezium/connect-jdbc-es:1.4
    container_name: icommerce-debezium
    build:
      context: debezium
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - mysql
      - elasticsearch
    environment:
      - BOOTSTRAP_SERVERS=${PRIVATE_HOST_IP}:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium_connect_configs
      - OFFSET_STORAGE_TOPIC=debezium_connect_offsets
      - STATUS_STORAGE_TOPIC=debezium_source_connect_statuses
    networks:
      - icommerce-network

  redis:
    image: redis:6.2.1-alpine
    container_name: icommerce-redis
    command: redis-server --appendonly yes --requirepass 6BEz9ED6BckEASTJ
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - icommerce-network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: icommerce_redisinsight
    ports:
      - 8081:8001
    depends_on:
      - redis
    networks:
      - icommerce-network

networks:
  icommerce-network:
    driver: bridge