server:
  port: 8100

grpc:
  port: 8101

spring:
  application:
    name: product-command-service
  datasource:
    url: jdbc:mysql://localhost:3306/nab_product
    username: root
    password: 123456789
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true