server:
  port: 8400

grpc:
  port: 8401

spring:
  application:
    name: customer-auditing-service
  elasticsearch:
    rest:
      uris: 52.77.250.133:9200
      username: elastic
      password: eEBrCXyeS6mmrZ7P

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    non-secure-port: ${grpc.port}