server:
  port: 8400

grpc:
  port: 8401

spring:
  application:
    name: customer-auditing-service
  elasticsearch:
    rest:
      uris: localhost:9200

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true