server:
  port: 8300

grpc:
  port: 8301

spring:
  application:
    name: cart-service
  redis:
    host: 52.77.250.133
    port: 6379
    username: default
    password: 6BEz9ED6BckEASTJ

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    non-secure-port: ${grpc.port}