server:
  port: 8300

grpc:
  port: 8301

spring:
  application:
    name: cart-service
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    non-secure-port: ${grpc.port}